"""empty message

Revision ID: 86dfc99a7189
Revises: ab2c390515e8
Create Date: 2019-01-08 20:30:35.211647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86dfc99a7189'
down_revision = 'ab2c390515e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result_sample', sa.Column('reason', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result_sample', 'reason')
    # ### end Alembic commands ###
